default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    -   id: black